#!/bin/bash
echo node index.js --start=$1 --end=$2 --users=$3
for i in $(seq $1 $2)
do	
	curl -O http://planet.openstreetmap.org/replication/day/000/000/$i.osc.gz
	gzip -d $i.osc.gz
done

echo node index.js --start=$1 --end=$2 --users=$3


for k in $(seq $1 $2)
do	
 	rm $k.osc
done
